### ISSUE TITLE
GetDnsDomains() not defined in interface SoftLayer_Account_Service

### ISSUE THREAD

**Issue by Huang-Wei** [maximilien/softlayer-go#125]
I noticed that method `GetDnsDomains()` is not defined in interface `SoftLayer_Account_Service` (softlayer_account_service.go), but implemented in `softlayer_account.go`. In this case, `GetDnsDomains()` can't be invoked from a `SoftLayer_Account_Service` interface object, right?

If you think it's worth adding the method, I can contribute a PR and unit tests.

**Comment by maximilien** [comment]
Hi, @Huang-Wei, yes this could be useful. However, please add it as `GetDomains()` (change current to that name) since the official name is `getDomains` from the [SL API docs](http://sldn.softlayer.com/reference/services/SoftLayer_Account/getDomains)

Also, please make sure to add some unit tests and possibly an integration test. The last one (integration test) can be tricky but are important since that's the only way to make sure code works OR to manually test it.

Let me know if you need help. Thanks in advance for contribution.

**Comment by Huang-Wei** [comment]
Thanks @maximilien, I've prepared a PR, please review.

BTW: I found some other issues in current integration tests:

#### domain test should expect an error when domain has been deleted

Look at https://github.com/maximilien/softlayer-go/blob/master/test_helpers/test_helpers.go#L701, it expected no errors. And I've changed `ToNot` to `To` in the PR.

#### `test.domain.records.name` already exists

I guess it was caused by somebody running domain tests. And I can confirm it's not under my sl account:

```
⇒  curl https://$username:$api_key@api.softlayer.com/rest/v3/SoftLayer_Dns_Domain/getByDomainName/test.domain.name
[]%                                                                                                                                                                         hweicdl@wei-mbp-ibm:~/gospace/src/github.com/maximilien/softlayer-go|master⚡
⇒  curl https://$username:$api_key@api.softlayer.com/rest/v3/SoftLayer_Dns_Domain/getByDomainName/test.domain.records.name
[]%
```

We can change `test.domain.records.name` to `delme.domain.records.name` to fix this if we cannot find who in deed holds this domain entry.

(BTW: I didn't include this change in PR)

**Comment by maximilien** [comment]
@Huang-Wei sounds reasonable. Please update PR with these. I will review and comment and/or merge. Best.

**Comment by Huang-Wei** [comment]
got it, commented in PR: https://github.com/maximilien/softlayer-go/pull/126#issuecomment-239336263
