### ISSUE TITLE
Programmatically Generated Types/Methods

### ISSUE THREAD

**Issue by sudorandom** [maximilien/softlayer-go#52]
I've been working on some go language bindings for the SoftLayer API as well and I just recently found this repo.

SoftLayer exposes metadata about the API that can be used programmatically create language bindings. The Java bindings are one example of the metadata being used this way: https://github.com/softlayer/softlayer-java. The metadata is available here: https://api.softlayer.com/metadata/v3.1.

On the go bindings I worked on I focused on auto-generating the types and service methods for all of SoftLayer's API. This results in extremely large structs and one very large package with all the types in it. Attempting to split them up proved near impossible since there are cyclic references within the API.
    E.G.: Accounts have VMs. VMs each have an account.

Anyway, here's a working example of what I have so far: https://github.com/sudorandom/softlayer-go. I just wanted to share what I have done in the hopes that it might help.

**Comment by maximilien** [comment]
Hi, 

Thanks for sharing. But you might have hit the reason why I created this project. The SL APIs is huge and complicated. And interestingly enough not all of it is needed, or used frequently. I think it's a case of 20% is often used and 80% rarely used or only used in special cases.

This project aims at creating a Golang client for the 20% or so that's needed and also make it easy to add new features as needed.

This is already being used in a few projects. It would make little sense to add the generated types since they (as you said) include too much and would require us to support (all) the APIs which would complicate things and go against our goal.

Cheers,

@maximilien

**Comment by sudorandom** [comment]
Cool, thanks for the reply. I have the same views toward the breadth of the SL API. That was the motivation behind the 'manager' concept in the softlayer-python library: https://github.com/sudorandom/softlayer-python/tree/master/SoftLayer/managers.
